let raw_trials =  [
    {
    "Trial_number":"1","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Hard","Body_1":"A","Face_1":"1","Body_2":"B","Face_2":"2","stimuli_1":"Face1_BodyA.png","stimuli_2":"Face2_BodyB.png","Corr_resp":"j"},
    {
    "Trial_number":"2","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Hard","Body_1":"A","Face_1":"2","Body_2":"B","Face_2":"1","stimuli_1":"Face2_BodyA.png","stimuli_2":"Face1_BodyB.png","Corr_resp":"j"},
    {
    "Trial_number":"3","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"A","Face_1":"1","Body_2":"B","Face_2":"1","stimuli_1":"Face1_BodyA.png","stimuli_2":"Face1_BodyB.png","Corr_resp":"j"},
    {
    "Trial_number":"4","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"A","Face_1":"2","Body_2":"B","Face_2":"2","stimuli_1":"Face2_BodyA.png","stimuli_2":"Face2_BodyB.png","Corr_resp":"j"},
    {
    "Trial_number":"5","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Medium","Body_1":"A","Face_1":"1","Body_2":"C","Face_2":"2","stimuli_1":"Face1_BodyA.png","stimuli_2":"Face2_BodyC.png","Corr_resp":"j"},
    {
    "Trial_number":"6","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Medium","Body_1":"A","Face_1":"2","Body_2":"C","Face_2":"1","stimuli_1":"Face2_BodyA.png","stimuli_2":"Face1_BodyC.png","Corr_resp":"j"},
    {
    "Trial_number":"7","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"A","Face_1":"1","Body_2":"C","Face_2":"1","stimuli_1":"Face1_BodyA.png","stimuli_2":"Face1_BodyC.png","Corr_resp":"j"},
    {
    "Trial_number":"8","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"A","Face_1":"2","Body_2":"C","Face_2":"2","stimuli_1":"Face2_BodyA.png","stimuli_2":"Face2_BodyC.png","Corr_resp":"j"},
    {
    "Trial_number":"9","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Easy","Body_1":"A","Face_1":"1","Body_2":"D","Face_2":"2","stimuli_1":"Face1_BodyA.png","stimuli_2":"Face2_BodyD.png","Corr_resp":"j"},
    {
    "Trial_number":"10","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Easy","Body_1":"A","Face_1":"2","Body_2":"D","Face_2":"1","stimuli_1":"Face2_BodyA.png","stimuli_2":"Face1_BodyD.png","Corr_resp":"j"},
    {
    "Trial_number":"11","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"A","Face_1":"1","Body_2":"D","Face_2":"1","stimuli_1":"Face1_BodyA.png","stimuli_2":"Face1_BodyD.png","Corr_resp":"j"},
    {
    "Trial_number":"12","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"A","Face_1":"2","Body_2":"D","Face_2":"2","stimuli_1":"Face2_BodyA.png","stimuli_2":"Face2_BodyD.png","Corr_resp":"j"},
    {
    "Trial_number":"13","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Hard","Body_1":"B","Face_1":"1","Body_2":"A","Face_2":"2","stimuli_1":"Face1_BodyB.png","stimuli_2":"Face2_BodyA.png","Corr_resp":"j"},
    {
    "Trial_number":"14","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Hard","Body_1":"B","Face_1":"2","Body_2":"A","Face_2":"1","stimuli_1":"Face2_BodyB.png","stimuli_2":"Face1_BodyA.png","Corr_resp":"j"},
    {
    "Trial_number":"15","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"B","Face_1":"1","Body_2":"A","Face_2":"1","stimuli_1":"Face1_BodyB.png","stimuli_2":"Face1_BodyA.png","Corr_resp":"j"},
    {
    "Trial_number":"16","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"B","Face_1":"2","Body_2":"A","Face_2":"2","stimuli_1":"Face2_BodyB.png","stimuli_2":"Face2_BodyA.png","Corr_resp":"j"},
    {
    "Trial_number":"17","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Medium","Body_1":"C","Face_1":"1","Body_2":"A","Face_2":"2","stimuli_1":"Face1_BodyC.png","stimuli_2":"Face2_BodyA.png","Corr_resp":"j"},
    {
    "Trial_number":"18","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Medium","Body_1":"C","Face_1":"2","Body_2":"A","Face_2":"1","stimuli_1":"Face2_BodyC.png","stimuli_2":"Face1_BodyA.png","Corr_resp":"j"},
    {
    "Trial_number":"19","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"C","Face_1":"1","Body_2":"A","Face_2":"1","stimuli_1":"Face1_BodyC.png","stimuli_2":"Face1_BodyA.png","Corr_resp":"j"},
    {
    "Trial_number":"20","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"C","Face_1":"2","Body_2":"A","Face_2":"2","stimuli_1":"Face2_BodyC.png","stimuli_2":"Face2_BodyA.png","Corr_resp":"j"},
    {
    "Trial_number":"21","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Easy","Body_1":"D","Face_1":"1","Body_2":"A","Face_2":"2","stimuli_1":"Face1_BodyD.png","stimuli_2":"Face2_BodyA.png","Corr_resp":"j"},
    {
    "Trial_number":"22","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Easy","Body_1":"D","Face_1":"2","Body_2":"A","Face_2":"1","stimuli_1":"Face2_BodyD.png","stimuli_2":"Face1_BodyA.png","Corr_resp":"j"},
    {
    "Trial_number":"23","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"D","Face_1":"1","Body_2":"A","Face_2":"1","stimuli_1":"Face1_BodyD.png","stimuli_2":"Face1_BodyA.png","Corr_resp":"j"},
    {
    "Trial_number":"24","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"D","Face_1":"2","Body_2":"A","Face_2":"2","stimuli_1":"Face2_BodyD.png","stimuli_2":"Face2_BodyA.png","Corr_resp":"j"},
    {
    "Trial_number":"25","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Hard","Body_1":"E","Face_1":"1","Body_2":"D","Face_2":"2","stimuli_1":"Face1_BodyE.png","stimuli_2":"Face2_BodyD.png","Corr_resp":"j"},
    {
    "Trial_number":"26","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Hard","Body_1":"E","Face_1":"2","Body_2":"D","Face_2":"1","stimuli_1":"Face2_BodyE.png","stimuli_2":"Face1_BodyD.png","Corr_resp":"j"},
    {
    "Trial_number":"27","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"E","Face_1":"1","Body_2":"D","Face_2":"1","stimuli_1":"Face1_BodyE.png","stimuli_2":"Face1_BodyD.png","Corr_resp":"j"},
    {
    "Trial_number":"28","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"E","Face_1":"2","Body_2":"D","Face_2":"2","stimuli_1":"Face2_BodyE.png","stimuli_2":"Face2_BodyD.png","Corr_resp":"j"},
    {
    "Trial_number":"29","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Medium","Body_1":"E","Face_1":"1","Body_2":"C","Face_2":"2","stimuli_1":"Face1_BodyE.png","stimuli_2":"Face2_BodyC.png","Corr_resp":"j"},
    {
    "Trial_number":"30","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Medium","Body_1":"E","Face_1":"2","Body_2":"C","Face_2":"1","stimuli_1":"Face2_BodyE.png","stimuli_2":"Face1_BodyC.png","Corr_resp":"j"},
    {
    "Trial_number":"31","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"E","Face_1":"1","Body_2":"C","Face_2":"1","stimuli_1":"Face1_BodyE.png","stimuli_2":"Face1_BodyC.png","Corr_resp":"j"},
    {
    "Trial_number":"32","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"E","Face_1":"2","Body_2":"C","Face_2":"2","stimuli_1":"Face2_BodyE.png","stimuli_2":"Face2_BodyC.png","Corr_resp":"j"},
    {
    "Trial_number":"33","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Easy","Body_1":"E","Face_1":"1","Body_2":"B","Face_2":"2","stimuli_1":"Face1_BodyE.png","stimuli_2":"Face2_BodyB.png","Corr_resp":"j"},
    {
    "Trial_number":"34","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Easy","Body_1":"E","Face_1":"2","Body_2":"B","Face_2":"1","stimuli_1":"Face2_BodyE.png","stimuli_2":"Face1_BodyB.png","Corr_resp":"j"},
    {
    "Trial_number":"35","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"E","Face_1":"1","Body_2":"B","Face_2":"1","stimuli_1":"Face1_BodyE.png","stimuli_2":"Face1_BodyB.png","Corr_resp":"j"},
    {
    "Trial_number":"36","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"E","Face_1":"2","Body_2":"B","Face_2":"2","stimuli_1":"Face2_BodyE.png","stimuli_2":"Face2_BodyB.png","Corr_resp":"j"},
    {
    "Trial_number":"37","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Hard","Body_1":"D","Face_1":"1","Body_2":"E","Face_2":"2","stimuli_1":"Face1_BodyD.png","stimuli_2":"Face2_BodyE.png","Corr_resp":"j"},
    {
    "Trial_number":"38","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Hard","Body_1":"D","Face_1":"2","Body_2":"E","Face_2":"1","stimuli_1":"Face2_BodyD.png","stimuli_2":"Face1_BodyE.png","Corr_resp":"j"},
    {
    "Trial_number":"39","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"D","Face_1":"1","Body_2":"E","Face_2":"1","stimuli_1":"Face1_BodyD.png","stimuli_2":"Face1_BodyE.png","Corr_resp":"j"},
    {
    "Trial_number":"40","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"D","Face_1":"2","Body_2":"E","Face_2":"2","stimuli_1":"Face2_BodyD.png","stimuli_2":"Face2_BodyE.png","Corr_resp":"j"},
    {
    "Trial_number":"41","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Medium","Body_1":"C","Face_1":"1","Body_2":"E","Face_2":"2","stimuli_1":"Face1_BodyC.png","stimuli_2":"Face2_BodyE.png","Corr_resp":"j"},
    {
    "Trial_number":"42","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Medium","Body_1":"C","Face_1":"2","Body_2":"E","Face_2":"1","stimuli_1":"Face2_BodyC.png","stimuli_2":"Face1_BodyE.png","Corr_resp":"j"},
    {
    "Trial_number":"43","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"C","Face_1":"1","Body_2":"E","Face_2":"1","stimuli_1":"Face1_BodyC.png","stimuli_2":"Face1_BodyE.png","Corr_resp":"j"},
    {
    "Trial_number":"44","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"C","Face_1":"2","Body_2":"E","Face_2":"2","stimuli_1":"Face2_BodyC.png","stimuli_2":"Face2_BodyE.png","Corr_resp":"j"},
    {
    "Trial_number":"45","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Easy","Body_1":"B","Face_1":"1","Body_2":"E","Face_2":"2","stimuli_1":"Face1_BodyB.png","stimuli_2":"Face2_BodyE.png","Corr_resp":"j"},
    {
    "Trial_number":"46","Trial_type":"Different","Alignment":"A","Congruency":"Congruent","Difficulty":"Easy","Body_1":"B","Face_1":"2","Body_2":"E","Face_2":"1","stimuli_1":"Face2_BodyB.png","stimuli_2":"Face1_BodyE.png","Corr_resp":"j"},
    {
    "Trial_number":"47","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"B","Face_1":"1","Body_2":"E","Face_2":"1","stimuli_1":"Face1_BodyB.png","stimuli_2":"Face1_BodyE.png","Corr_resp":"j"},
    {
    "Trial_number":"48","Trial_type":"Different","Alignment":"A","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"B","Face_1":"2","Body_2":"E","Face_2":"2","stimuli_1":"Face2_BodyB.png","stimuli_2":"Face2_BodyE.png","Corr_resp":"j"},
    {
    "Trial_number":"49","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Easy","Body_1":"A","Face_1":"1","Body_2":"D","Face_2":"2","stimuli_1":"Face1_BodyA_M.png","stimuli_2":"Face2_BodyD_M.png","Corr_resp":"j"},
    {
    "Trial_number":"50","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Easy","Body_1":"A","Face_1":"2","Body_2":"D","Face_2":"1","stimuli_1":"Face2_BodyA_M.png","stimuli_2":"Face1_BodyD_M.png","Corr_resp":"j"},
    {
    "Trial_number":"51","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"A","Face_1":"1","Body_2":"D","Face_2":"1","stimuli_1":"Face1_BodyA_M.png","stimuli_2":"Face1_BodyD_M.png","Corr_resp":"j"},
    {
    "Trial_number":"52","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"A","Face_1":"2","Body_2":"D","Face_2":"2","stimuli_1":"Face2_BodyA_M.png","stimuli_2":"Face2_BodyD_M.png","Corr_resp":"j"},
    {
    "Trial_number":"53","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Medium","Body_1":"A","Face_1":"1","Body_2":"C","Face_2":"2","stimuli_1":"Face1_BodyA_M.png","stimuli_2":"Face2_BodyC_M.png","Corr_resp":"j"},
    {
    "Trial_number":"54","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Medium","Body_1":"A","Face_1":"2","Body_2":"C","Face_2":"1","stimuli_1":"Face2_BodyA_M.png","stimuli_2":"Face1_BodyC_M.png","Corr_resp":"j"},
    {
    "Trial_number":"55","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"A","Face_1":"1","Body_2":"C","Face_2":"1","stimuli_1":"Face1_BodyA_M.png","stimuli_2":"Face1_BodyC_M.png","Corr_resp":"j"},
    {
    "Trial_number":"56","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"A","Face_1":"2","Body_2":"C","Face_2":"2","stimuli_1":"Face2_BodyA_M.png","stimuli_2":"Face2_BodyC_M.png","Corr_resp":"j"},
    {
    "Trial_number":"57","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Hard","Body_1":"A","Face_1":"1","Body_2":"B","Face_2":"2","stimuli_1":"Face1_BodyA_M.png","stimuli_2":"Face2_BodyB_M.png","Corr_resp":"j"},
    {
    "Trial_number":"58","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Hard","Body_1":"A","Face_1":"2","Body_2":"B","Face_2":"1","stimuli_1":"Face2_BodyA_M.png","stimuli_2":"Face1_BodyB_M.png","Corr_resp":"j"},
    {
    "Trial_number":"59","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"A","Face_1":"1","Body_2":"B","Face_2":"1","stimuli_1":"Face1_BodyA_M.png","stimuli_2":"Face1_BodyB_M.png","Corr_resp":"j"},
    {
    "Trial_number":"60","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"A","Face_1":"2","Body_2":"B","Face_2":"2","stimuli_1":"Face2_BodyA_M.png","stimuli_2":"Face2_BodyB_M.png","Corr_resp":"j"},
    {
    "Trial_number":"61","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Hard","Body_1":"B","Face_1":"1","Body_2":"A","Face_2":"2","stimuli_1":"Face1_BodyB_M.png","stimuli_2":"Face2_BodyA_M.png","Corr_resp":"j"},
    {
    "Trial_number":"62","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Hard","Body_1":"B","Face_1":"2","Body_2":"A","Face_2":"1","stimuli_1":"Face2_BodyB_M.png","stimuli_2":"Face1_BodyA_M.png","Corr_resp":"j"},
    {
    "Trial_number":"63","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"B","Face_1":"1","Body_2":"A","Face_2":"1","stimuli_1":"Face1_BodyB_M.png","stimuli_2":"Face1_BodyA_M.png","Corr_resp":"j"},
    {
    "Trial_number":"64","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"B","Face_1":"2","Body_2":"A","Face_2":"2","stimuli_1":"Face2_BodyB_M.png","stimuli_2":"Face2_BodyA_M.png","Corr_resp":"j"},
    {
    "Trial_number":"65","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Medium","Body_1":"C","Face_1":"1","Body_2":"A","Face_2":"2","stimuli_1":"Face1_BodyC_M.png","stimuli_2":"Face2_BodyA_M.png","Corr_resp":"j"},
    {
    "Trial_number":"66","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Medium","Body_1":"C","Face_1":"2","Body_2":"A","Face_2":"1","stimuli_1":"Face2_BodyC_M.png","stimuli_2":"Face1_BodyA_M.png","Corr_resp":"j"},
    {
    "Trial_number":"67","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"C","Face_1":"1","Body_2":"A","Face_2":"1","stimuli_1":"Face1_BodyC_M.png","stimuli_2":"Face1_BodyA_M.png","Corr_resp":"j"},
    {
    "Trial_number":"68","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"C","Face_1":"2","Body_2":"A","Face_2":"2","stimuli_1":"Face2_BodyC_M.png","stimuli_2":"Face2_BodyA_M.png","Corr_resp":"j"},
    {
    "Trial_number":"69","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Easy","Body_1":"D","Face_1":"1","Body_2":"A","Face_2":"2","stimuli_1":"Face1_BodyD_M.png","stimuli_2":"Face2_BodyA_M.png","Corr_resp":"j"},
    {
    "Trial_number":"70","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Easy","Body_1":"D","Face_1":"2","Body_2":"A","Face_2":"1","stimuli_1":"Face2_BodyD_M.png","stimuli_2":"Face1_BodyA_M.png","Corr_resp":"j"},
    {
    "Trial_number":"71","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"D","Face_1":"1","Body_2":"A","Face_2":"1","stimuli_1":"Face1_BodyD_M.png","stimuli_2":"Face1_BodyA_M.png","Corr_resp":"j"},
    {
    "Trial_number":"72","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"D","Face_1":"2","Body_2":"A","Face_2":"2","stimuli_1":"Face2_BodyD_M.png","stimuli_2":"Face2_BodyA_M.png","Corr_resp":"j"},
    {
    "Trial_number":"73","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Hard","Body_1":"E","Face_1":"1","Body_2":"D","Face_2":"2","stimuli_1":"Face1_BodyE_M.png","stimuli_2":"Face2_BodyD_M.png","Corr_resp":"j"},
    {
    "Trial_number":"74","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Hard","Body_1":"E","Face_1":"2","Body_2":"D","Face_2":"1","stimuli_1":"Face2_BodyE_M.png","stimuli_2":"Face1_BodyD_M.png","Corr_resp":"j"},
    {
    "Trial_number":"75","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"E","Face_1":"1","Body_2":"D","Face_2":"1","stimuli_1":"Face1_BodyE_M.png","stimuli_2":"Face1_BodyD_M.png","Corr_resp":"j"},
    {
    "Trial_number":"76","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"E","Face_1":"2","Body_2":"D","Face_2":"2","stimuli_1":"Face2_BodyE_M.png","stimuli_2":"Face2_BodyD_M.png","Corr_resp":"j"},
    {
    "Trial_number":"77","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Medium","Body_1":"E","Face_1":"1","Body_2":"C","Face_2":"2","stimuli_1":"Face1_BodyE_M.png","stimuli_2":"Face2_BodyC_M.png","Corr_resp":"j"},
    {
    "Trial_number":"78","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Medium","Body_1":"E","Face_1":"2","Body_2":"C","Face_2":"1","stimuli_1":"Face2_BodyE_M.png","stimuli_2":"Face1_BodyC_M.png","Corr_resp":"j"},
    {
    "Trial_number":"79","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"E","Face_1":"1","Body_2":"C","Face_2":"1","stimuli_1":"Face1_BodyE_M.png","stimuli_2":"Face1_BodyC_M.png","Corr_resp":"j"},
    {
    "Trial_number":"80","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"E","Face_1":"2","Body_2":"C","Face_2":"2","stimuli_1":"Face2_BodyE_M.png","stimuli_2":"Face2_BodyC_M.png","Corr_resp":"j"},
    {
    "Trial_number":"81","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Easy","Body_1":"E","Face_1":"1","Body_2":"B","Face_2":"2","stimuli_1":"Face1_BodyE_M.png","stimuli_2":"Face2_BodyB_M.png","Corr_resp":"j"},
    {
    "Trial_number":"82","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Easy","Body_1":"E","Face_1":"2","Body_2":"B","Face_2":"1","stimuli_1":"Face2_BodyE_M.png","stimuli_2":"Face1_BodyB_M.png","Corr_resp":"j"},
    {
    "Trial_number":"83","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"E","Face_1":"1","Body_2":"B","Face_2":"1","stimuli_1":"Face1_BodyE_M.png","stimuli_2":"Face1_BodyB_M.png","Corr_resp":"j"},
    {
    "Trial_number":"84","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"E","Face_1":"2","Body_2":"B","Face_2":"2","stimuli_1":"Face2_BodyE_M.png","stimuli_2":"Face2_BodyB_M.png","Corr_resp":"j"},
    {
    "Trial_number":"85","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Hard","Body_1":"D","Face_1":"1","Body_2":"E","Face_2":"2","stimuli_1":"Face1_BodyD_M.png","stimuli_2":"Face2_BodyE_M.png","Corr_resp":"j"},
    {
    "Trial_number":"86","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Hard","Body_1":"D","Face_1":"2","Body_2":"E","Face_2":"1","stimuli_1":"Face2_BodyD_M.png","stimuli_2":"Face1_BodyE_M.png","Corr_resp":"j"},
    {
    "Trial_number":"87","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"D","Face_1":"1","Body_2":"E","Face_2":"1","stimuli_1":"Face1_BodyD_M.png","stimuli_2":"Face1_BodyE_M.png","Corr_resp":"j"},
    {
    "Trial_number":"88","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Hard","Body_1":"D","Face_1":"2","Body_2":"E","Face_2":"2","stimuli_1":"Face2_BodyD_M.png","stimuli_2":"Face2_BodyE_M.png","Corr_resp":"j"},
    {
    "Trial_number":"89","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Medium","Body_1":"C","Face_1":"1","Body_2":"E","Face_2":"2","stimuli_1":"Face1_BodyC_M.png","stimuli_2":"Face2_BodyE_M.png","Corr_resp":"j"},
    {
    "Trial_number":"90","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Medium","Body_1":"C","Face_1":"2","Body_2":"E","Face_2":"1","stimuli_1":"Face2_BodyC_M.png","stimuli_2":"Face1_BodyE_M.png","Corr_resp":"j"},
    {
    "Trial_number":"91","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"C","Face_1":"1","Body_2":"E","Face_2":"1","stimuli_1":"Face1_BodyC_M.png","stimuli_2":"Face1_BodyE_M.png","Corr_resp":"j"},
    {
    "Trial_number":"92","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Medium","Body_1":"C","Face_1":"2","Body_2":"E","Face_2":"2","stimuli_1":"Face2_BodyC_M.png","stimuli_2":"Face2_BodyE_M.png","Corr_resp":"j"},
    {
    "Trial_number":"93","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Easy","Body_1":"B","Face_1":"1","Body_2":"E","Face_2":"2","stimuli_1":"Face1_BodyB_M.png","stimuli_2":"Face2_BodyE_M.png","Corr_resp":"j"},
    {
    "Trial_number":"94","Trial_type":"Different","Alignment":"M","Congruency":"Congruent","Difficulty":"Easy","Body_1":"B","Face_1":"2","Body_2":"E","Face_2":"1","stimuli_1":"Face2_BodyB_M.png","stimuli_2":"Face1_BodyE_M.png","Corr_resp":"j"},
    {
    "Trial_number":"95","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"B","Face_1":"1","Body_2":"E","Face_2":"1","stimuli_1":"Face1_BodyB_M.png","stimuli_2":"Face1_BodyE_M.png","Corr_resp":"j"},
    {
    "Trial_number":"96","Trial_type":"Different","Alignment":"M","Congruency":"Incongruent","Difficulty":"Easy","Body_1":"B","Face_1":"2","Body_2":"E","Face_2":"2","stimuli_1":"Face2_BodyB_M.png","stimuli_2":"Face2_BodyE_M.png","Corr_resp":"j"},
    {
    "Trial_number":"97","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"A","Face_1":"1","Body_2":"A","Face_2":"2","stimuli_1":"Face1_BodyA.png","stimuli_2":"Face2_BodyA.png","Corr_resp":"f"},
    {
    "Trial_number":"98","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"A","Face_1":"2","Body_2":"A","Face_2":"1","stimuli_1":"Face2_BodyA.png","stimuli_2":"Face1_BodyA.png","Corr_resp":"f"},
    {
    "Trial_number":"99","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"A","Face_1":"1","Body_2":"A","Face_2":"1","stimuli_1":"Face1_BodyA.png","stimuli_2":"Face1_BodyA.png","Corr_resp":"f"},
    {
    "Trial_number":"100","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"A","Face_1":"2","Body_2":"A","Face_2":"2","stimuli_1":"Face2_BodyA.png","stimuli_2":"Face2_BodyA.png","Corr_resp":"f"},
    {
    "Trial_number":"101","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"E","Face_1":"1","Body_2":"E","Face_2":"2","stimuli_1":"Face1_BodyE.png","stimuli_2":"Face2_BodyE.png","Corr_resp":"f"},
    {
    "Trial_number":"102","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"E","Face_1":"2","Body_2":"E","Face_2":"1","stimuli_1":"Face2_BodyE.png","stimuli_2":"Face1_BodyE.png","Corr_resp":"f"},
    {
    "Trial_number":"103","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"E","Face_1":"1","Body_2":"E","Face_2":"1","stimuli_1":"Face1_BodyE.png","stimuli_2":"Face1_BodyE.png","Corr_resp":"f"},
    {
    "Trial_number":"104","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"E","Face_1":"2","Body_2":"E","Face_2":"2","stimuli_1":"Face2_BodyE.png","stimuli_2":"Face2_BodyE.png","Corr_resp":"f"},
    {
    "Trial_number":"105","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"B","Face_1":"1","Body_2":"B","Face_2":"2","stimuli_1":"Face1_BodyB.png","stimuli_2":"Face2_BodyB.png","Corr_resp":"f"},
    {
    "Trial_number":"106","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"B","Face_1":"2","Body_2":"B","Face_2":"1","stimuli_1":"Face2_BodyB.png","stimuli_2":"Face1_BodyB.png","Corr_resp":"f"},
    {
    "Trial_number":"107","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"B","Face_1":"1","Body_2":"B","Face_2":"1","stimuli_1":"Face1_BodyB.png","stimuli_2":"Face1_BodyB.png","Corr_resp":"f"},
    {
    "Trial_number":"108","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"B","Face_1":"2","Body_2":"B","Face_2":"2","stimuli_1":"Face2_BodyB.png","stimuli_2":"Face2_BodyB.png","Corr_resp":"f"},
    {
    "Trial_number":"109","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"C","Face_1":"1","Body_2":"C","Face_2":"2","stimuli_1":"Face1_BodyC.png","stimuli_2":"Face2_BodyC.png","Corr_resp":"f"},
    {
    "Trial_number":"110","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"C","Face_1":"2","Body_2":"C","Face_2":"1","stimuli_1":"Face2_BodyC.png","stimuli_2":"Face1_BodyC.png","Corr_resp":"f"},
    {
    "Trial_number":"111","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"C","Face_1":"1","Body_2":"C","Face_2":"1","stimuli_1":"Face1_BodyC.png","stimuli_2":"Face1_BodyC.png","Corr_resp":"f"},
    {
    "Trial_number":"112","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"C","Face_1":"2","Body_2":"C","Face_2":"2","stimuli_1":"Face2_BodyC.png","stimuli_2":"Face2_BodyC.png","Corr_resp":"f"},
    {
    "Trial_number":"113","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"D","Face_1":"1","Body_2":"D","Face_2":"2","stimuli_1":"Face1_BodyD.png","stimuli_2":"Face2_BodyD.png","Corr_resp":"f"},
    {
    "Trial_number":"114","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"D","Face_1":"2","Body_2":"D","Face_2":"1","stimuli_1":"Face2_BodyD.png","stimuli_2":"Face1_BodyD.png","Corr_resp":"f"},
    {
    "Trial_number":"115","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"D","Face_1":"1","Body_2":"D","Face_2":"1","stimuli_1":"Face1_BodyD.png","stimuli_2":"Face1_BodyD.png","Corr_resp":"f"},
    {
    "Trial_number":"116","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"D","Face_1":"2","Body_2":"D","Face_2":"2","stimuli_1":"Face2_BodyD.png","stimuli_2":"Face2_BodyD.png","Corr_resp":"f"},
    {
    "Trial_number":"117","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"A","Face_1":"1","Body_2":"A","Face_2":"2","stimuli_1":"Face1_BodyA_M.png","stimuli_2":"Face2_BodyA_M.png","Corr_resp":"f"},
    {
    "Trial_number":"118","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"A","Face_1":"2","Body_2":"A","Face_2":"1","stimuli_1":"Face2_BodyA_M.png","stimuli_2":"Face1_BodyA_M.png","Corr_resp":"f"},
    {
    "Trial_number":"119","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"A","Face_1":"1","Body_2":"A","Face_2":"1","stimuli_1":"Face1_BodyA_M.png","stimuli_2":"Face1_BodyA_M.png","Corr_resp":"f"},
    {
    "Trial_number":"120","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"A","Face_1":"2","Body_2":"A","Face_2":"2","stimuli_1":"Face2_BodyA_M.png","stimuli_2":"Face2_BodyA_M.png","Corr_resp":"f"},
    {
    "Trial_number":"121","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"E","Face_1":"1","Body_2":"E","Face_2":"2","stimuli_1":"Face1_BodyE_M.png","stimuli_2":"Face2_BodyE_M.png","Corr_resp":"f"},
    {
    "Trial_number":"122","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"E","Face_1":"2","Body_2":"E","Face_2":"1","stimuli_1":"Face2_BodyE_M.png","stimuli_2":"Face1_BodyE_M.png","Corr_resp":"f"},
    {
    "Trial_number":"123","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"E","Face_1":"1","Body_2":"E","Face_2":"1","stimuli_1":"Face1_BodyE_M.png","stimuli_2":"Face1_BodyE_M.png","Corr_resp":"f"},
    {
    "Trial_number":"124","Trial_type":"Same","Alignment":"M","Congruency":"Ccongruent","Difficulty":"Same","Body_1":"E","Face_1":"2","Body_2":"E","Face_2":"2","stimuli_1":"Face2_BodyE_M.png","stimuli_2":"Face2_BodyE_M.png","Corr_resp":"f"},
    {
    "Trial_number":"125","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"B","Face_1":"1","Body_2":"D","Face_2":"2","stimuli_1":"Face1_BodyB_M.png","stimuli_2":"Face2_BodyB_M.png","Corr_resp":"f"},
    {
    "Trial_number":"126","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"B","Face_1":"2","Body_2":"D","Face_2":"1","stimuli_1":"Face2_BodyB_M.png","stimuli_2":"Face1_BodyB_M.png","Corr_resp":"f"},
    {
    "Trial_number":"127","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"B","Face_1":"1","Body_2":"D","Face_2":"1","stimuli_1":"Face1_BodyB_M.png","stimuli_2":"Face1_BodyB_M.png","Corr_resp":"f"},
    {
    "Trial_number":"128","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"B","Face_1":"2","Body_2":"D","Face_2":"2","stimuli_1":"Face2_BodyB_M.png","stimuli_2":"Face2_BodyB_M.png","Corr_resp":"f"},
    {
    "Trial_number":"129","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"C","Face_1":"1","Body_2":"C","Face_2":"2","stimuli_1":"Face1_BodyC_M.png","stimuli_2":"Face2_BodyC_M.png","Corr_resp":"f"},
    {
    "Trial_number":"130","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"C","Face_1":"2","Body_2":"C","Face_2":"1","stimuli_1":"Face2_BodyC_M.png","stimuli_2":"Face1_BodyC_M.png","Corr_resp":"f"},
    {
    "Trial_number":"131","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"C","Face_1":"1","Body_2":"C","Face_2":"1","stimuli_1":"Face1_BodyC_M.png","stimuli_2":"Face1_BodyC_M.png","Corr_resp":"f"},
    {
    "Trial_number":"132","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"C","Face_1":"2","Body_2":"C","Face_2":"2","stimuli_1":"Face2_BodyC_M.png","stimuli_2":"Face2_BodyC_M.png","Corr_resp":"f"},
    {
    "Trial_number":"133","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"D","Face_1":"1","Body_2":"B","Face_2":"2","stimuli_1":"Face1_BodyD_M.png","stimuli_2":"Face2_BodyD_M.png","Corr_resp":"f"},
    {
    "Trial_number":"134","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"D","Face_1":"2","Body_2":"B","Face_2":"1","stimuli_1":"Face2_BodyD_M.png","stimuli_2":"Face1_BodyD_M.png","Corr_resp":"f"},
    {
    "Trial_number":"135","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"D","Face_1":"1","Body_2":"B","Face_2":"1","stimuli_1":"Face1_BodyD_M.png","stimuli_2":"Face1_BodyD_M.png","Corr_resp":"f"},
    {
    "Trial_number":"136","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"D","Face_1":"2","Body_2":"B","Face_2":"2","stimuli_1":"Face2_BodyD_M.png","stimuli_2":"Face2_BodyD_M.png","Corr_resp":"f"},
    {
    "Trial_number":"137","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"A","Face_1":"1","Body_2":"A","Face_2":"2","stimuli_1":"Face1_BodyA.png","stimuli_2":"Face2_BodyA.png","Corr_resp":"f"},
    {
    "Trial_number":"138","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"A","Face_1":"2","Body_2":"A","Face_2":"1","stimuli_1":"Face2_BodyA.png","stimuli_2":"Face1_BodyA.png","Corr_resp":"f"},
    {
    "Trial_number":"139","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"A","Face_1":"1","Body_2":"A","Face_2":"1","stimuli_1":"Face1_BodyA.png","stimuli_2":"Face1_BodyA.png","Corr_resp":"f"},
    {
    "Trial_number":"140","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"A","Face_1":"2","Body_2":"A","Face_2":"2","stimuli_1":"Face2_BodyA.png","stimuli_2":"Face2_BodyA.png","Corr_resp":"f"},
    {
    "Trial_number":"141","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"E","Face_1":"1","Body_2":"E","Face_2":"2","stimuli_1":"Face1_BodyE.png","stimuli_2":"Face2_BodyE.png","Corr_resp":"f"},
    {
    "Trial_number":"142","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"E","Face_1":"2","Body_2":"E","Face_2":"1","stimuli_1":"Face2_BodyE.png","stimuli_2":"Face1_BodyE.png","Corr_resp":"f"},
    {
    "Trial_number":"143","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"E","Face_1":"1","Body_2":"E","Face_2":"1","stimuli_1":"Face1_BodyE.png","stimuli_2":"Face1_BodyE.png","Corr_resp":"f"},
    {
    "Trial_number":"144","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"E","Face_1":"2","Body_2":"E","Face_2":"2","stimuli_1":"Face2_BodyE.png","stimuli_2":"Face2_BodyE.png","Corr_resp":"f"},
    {
    "Trial_number":"145","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"B","Face_1":"1","Body_2":"B","Face_2":"2","stimuli_1":"Face1_BodyB.png","stimuli_2":"Face2_BodyB.png","Corr_resp":"f"},
    {
    "Trial_number":"146","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"B","Face_1":"2","Body_2":"B","Face_2":"1","stimuli_1":"Face2_BodyB.png","stimuli_2":"Face1_BodyB.png","Corr_resp":"f"},
    {
    "Trial_number":"147","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"B","Face_1":"1","Body_2":"B","Face_2":"1","stimuli_1":"Face1_BodyB.png","stimuli_2":"Face1_BodyB.png","Corr_resp":"f"},
    {
    "Trial_number":"148","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"B","Face_1":"2","Body_2":"B","Face_2":"2","stimuli_1":"Face2_BodyB.png","stimuli_2":"Face2_BodyB.png","Corr_resp":"f"},
    {
    "Trial_number":"149","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"C","Face_1":"1","Body_2":"C","Face_2":"2","stimuli_1":"Face1_BodyC.png","stimuli_2":"Face2_BodyC.png","Corr_resp":"f"},
    {
    "Trial_number":"150","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"C","Face_1":"2","Body_2":"C","Face_2":"1","stimuli_1":"Face2_BodyC.png","stimuli_2":"Face1_BodyC.png","Corr_resp":"f"},
    {
    "Trial_number":"151","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"C","Face_1":"1","Body_2":"C","Face_2":"1","stimuli_1":"Face1_BodyC.png","stimuli_2":"Face1_BodyC.png","Corr_resp":"f"},
    {
    "Trial_number":"152","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"C","Face_1":"2","Body_2":"C","Face_2":"2","stimuli_1":"Face2_BodyC.png","stimuli_2":"Face2_BodyC.png","Corr_resp":"f"},
    {
    "Trial_number":"153","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"D","Face_1":"1","Body_2":"D","Face_2":"2","stimuli_1":"Face1_BodyD.png","stimuli_2":"Face2_BodyD.png","Corr_resp":"f"},
    {
    "Trial_number":"154","Trial_type":"Same","Alignment":"A","Congruency":"Incongruent","Difficulty":"Same","Body_1":"D","Face_1":"2","Body_2":"D","Face_2":"1","stimuli_1":"Face2_BodyD.png","stimuli_2":"Face1_BodyD.png","Corr_resp":"f"},
    {
    "Trial_number":"155","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"D","Face_1":"1","Body_2":"D","Face_2":"1","stimuli_1":"Face1_BodyD.png","stimuli_2":"Face1_BodyD.png","Corr_resp":"f"},
    {
    "Trial_number":"156","Trial_type":"Same","Alignment":"A","Congruency":"Congruent","Difficulty":"Same","Body_1":"D","Face_1":"2","Body_2":"D","Face_2":"2","stimuli_1":"Face2_BodyD.png","stimuli_2":"Face2_BodyD.png","Corr_resp":"f"},
    {
    "Trial_number":"157","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"A","Face_1":"1","Body_2":"A","Face_2":"2","stimuli_1":"Face1_BodyA_M.png","stimuli_2":"Face2_BodyA_M.png","Corr_resp":"f"},
    {
    "Trial_number":"158","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"A","Face_1":"2","Body_2":"A","Face_2":"1","stimuli_1":"Face2_BodyA_M.png","stimuli_2":"Face1_BodyA_M.png","Corr_resp":"f"},
    {
    "Trial_number":"159","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"A","Face_1":"1","Body_2":"A","Face_2":"1","stimuli_1":"Face1_BodyA_M.png","stimuli_2":"Face1_BodyA_M.png","Corr_resp":"f"},
    {
    "Trial_number":"160","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"A","Face_1":"2","Body_2":"A","Face_2":"2","stimuli_1":"Face2_BodyA_M.png","stimuli_2":"Face2_BodyA_M.png","Corr_resp":"f"},
    {
    "Trial_number":"161","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"E","Face_1":"1","Body_2":"E","Face_2":"2","stimuli_1":"Face1_BodyE_M.png","stimuli_2":"Face2_BodyE_M.png","Corr_resp":"f"},
    {
    "Trial_number":"162","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"E","Face_1":"2","Body_2":"E","Face_2":"1","stimuli_1":"Face2_BodyE_M.png","stimuli_2":"Face1_BodyE_M.png","Corr_resp":"f"},
    {
    "Trial_number":"163","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"E","Face_1":"1","Body_2":"E","Face_2":"1","stimuli_1":"Face1_BodyE_M.png","stimuli_2":"Face1_BodyE_M.png","Corr_resp":"f"},
    {
    "Trial_number":"164","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"E","Face_1":"2","Body_2":"E","Face_2":"2","stimuli_1":"Face2_BodyE_M.png","stimuli_2":"Face2_BodyE_M.png","Corr_resp":"f"},
    {
    "Trial_number":"165","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"D","Face_1":"1","Body_2":"D","Face_2":"2","stimuli_1":"Face1_BodyB_M.png","stimuli_2":"Face2_BodyB_M.png","Corr_resp":"f"},
    {
    "Trial_number":"166","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"D","Face_1":"2","Body_2":"D","Face_2":"1","stimuli_1":"Face2_BodyB_M.png","stimuli_2":"Face1_BodyB_M.png","Corr_resp":"f"},
    {
    "Trial_number":"167","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"D","Face_1":"1","Body_2":"D","Face_2":"1","stimuli_1":"Face1_BodyB_M.png","stimuli_2":"Face1_BodyB_M.png","Corr_resp":"f"},
    {
    "Trial_number":"168","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"D","Face_1":"2","Body_2":"D","Face_2":"2","stimuli_1":"Face2_BodyB_M.png","stimuli_2":"Face2_BodyB_M.png","Corr_resp":"f"},
    {
    "Trial_number":"169","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"C","Face_1":"1","Body_2":"C","Face_2":"2","stimuli_1":"Face1_BodyC_M.png","stimuli_2":"Face2_BodyC_M.png","Corr_resp":"f"},
    {
    "Trial_number":"170","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"C","Face_1":"2","Body_2":"C","Face_2":"1","stimuli_1":"Face2_BodyC_M.png","stimuli_2":"Face1_BodyC_M.png","Corr_resp":"f"},
    {
    "Trial_number":"171","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"C","Face_1":"1","Body_2":"C","Face_2":"1","stimuli_1":"Face1_BodyC_M.png","stimuli_2":"Face1_BodyC_M.png","Corr_resp":"f"},
    {
    "Trial_number":"172","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"C","Face_1":"2","Body_2":"C","Face_2":"2","stimuli_1":"Face2_BodyC_M.png","stimuli_2":"Face2_BodyC_M.png","Corr_resp":"f"},
    {
    "Trial_number":"173","Trial_type":"Same","Alignment":"M","Congruency":"Incongruent","Difficulty":"Same","Body_1":"B","Face_1":"1","Body_2":"B","Face_2":"2","stimuli_1":"Face1_BodyD_M.png","stimuli_2":"Face2_BodyD_M.png","Corr_resp":"f"},
    {
    "Trial_number":"174","Trial_type":"Same","Alignment":"M","Congruency":"Inconngruent","Difficulty":"Same","Body_1":"B","Face_1":"2","Body_2":"B","Face_2":"1","stimuli_1":"Face2_BodyD_M.png","stimuli_2":"Face1_BodyD_M.png","Corr_resp":"f"},
    {
    "Trial_number":"175","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"B","Face_1":"1","Body_2":"B","Face_2":"1","stimuli_1":"Face1_BodyD_M.png","stimuli_2":"Face1_BodyD_M.png","Corr_resp":"f"},
    {
    "Trial_number":"176","Trial_type":"Same","Alignment":"M","Congruency":"Congruent","Difficulty":"Same","Body_1":"B","Face_1":"2","Body_2":"B","Face_2":"2","stimuli_1":"Face2_BodyD_M.png","stimuli_2":"Face2_BodyD_M.png","Corr_resp":"f"},
    ]
